// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://migwubhrggmqiwxnqcot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZ3d1YmhyZ2dtcWl3eG5xY290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzUxOTYsImV4cCI6MjA1MzE1MTE5Nn0.EukxE21QjKbop119FjX6SzUjcUCoYUJG2lakYtW1F8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);